extends: spectral:oas

rules:

- id: oas3-api-servers
  description: OpenAPI servers must be present and non-empty array.
  severity: error
  given:
    - $.servers
  then:
    - type: is_array
    - value: true
    - message: "The OpenAPI servers must be present and non-empty array."

- id: oas3-paths-must-be-kebab-case
  description: All paths must be in kebab-case.
  severity: warning
  given:
    - $.paths
  then:
    - type: all_paths_are_kebab_case
    - message: "All paths must be in kebab-case."

- id: oas3-responses-must-have-description
  description: All responses must have a description.
  severity: warning
  given:
    - $.responses
  then:
    - type: all_responses_have_description
    - message: "All responses must have a description."

